# Generated by Django 5.2 on 2025-05-09 09:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paczkomatyapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryhistory',
            old_name='parcel_id',
            new_name='parcel',
        ),
        migrations.AddField(
            model_name='deliveryhistory',
            name='event_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliveryhistory',
            name='event_type',
            field=models.CharField(choices=[('created', 'created'), ('placed_in_locker', 'placed_in_locker'), ('picked_up', 'picked_up')], max_length=30),
        ),
        migrations.AlterField(
            model_name='locker_slot',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=30),
        ),
        migrations.AlterField(
            model_name='locker_slot',
            name='slot_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='pickup_code',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='receiver_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='sender_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('awaiting_pickup', 'awaiting_pickup'), ('picked_up', 'picked_up'), ('in_transit', 'in_transit'), ('delivered', 'delivered')], default='in_transit', max_length=30),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='tracking_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='parcel_locker',
            name='location',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='parcel_locker',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
