# Generated by Django 5.2 on 2025-05-10 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paczkomatyapp', '0002_rename_parcel_id_deliveryhistory_parcel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='receiver_name',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='sender_name',
        ),
        migrations.AddField(
            model_name='locker_slot',
            name='parcel_locker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paczkomatyapp.parcel_locker'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_parcels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parcel',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_parcels', to=settings.AUTH_USER_MODEL),
        ),
    ]
