# Generated by Django 5.2 on 2025-05-10 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paczkomatyapp', '0003_remove_parcel_receiver_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LockerSlot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slot_number', models.CharField(max_length=30)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=6)),
                ('is_occupied', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParcelLocker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=9)),
                ('status', models.BooleanField(default=False)),
                ('number_of_slots', models.PositiveIntegerField(default=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='locker_slot',
            name='parcel_locker',
        ),
        migrations.AlterField(
            model_name='deliveryhistory',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('placed_in_locker', 'Placed in Locker'), ('picked_up', 'Picked Up')], max_length=20),
        ),
        migrations.AlterField(
            model_name='deliveryhistory',
            name='parcel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='paczkomatyapp.parcel'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('awaiting_pickup', 'Awaiting Pickup'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], default='in_transit', max_length=20),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='locker_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='paczkomatyapp.lockerslot'),
        ),
        migrations.AddField(
            model_name='lockerslot',
            name='parcel_locker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='paczkomatyapp.parcellocker'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='parcel_locker',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='paczkomatyapp.parcellocker'),
        ),
        migrations.DeleteModel(
            name='Parcel_Locker',
        ),
        migrations.DeleteModel(
            name='Locker_Slot',
        ),
    ]
