# Generated by Django 5.2 on 2025-05-10 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paczkomatyapp', '0004_lockerslot_parcellocker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=6),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='locker_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paczkomatyapp.lockerslot'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='parcel_locker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paczkomatyapp.parcellocker'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('awaiting_pickup', 'Awaiting Pickup'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], default='in_transit', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='lockerslot',
            constraint=models.UniqueConstraint(fields=('parcel_locker', 'slot_number'), name='unique_slot_per_locker'),
        ),
    ]
