# Generated by Django 5.2 on 2025-05-09 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locker_Slot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slot_number', models.CharField(max_length=10)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=20)),
                ('is_occupied', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parcel_Locker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=9)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('awaiting_pickup', 'awaiting_pickup'), ('picked_up', 'picked_up'), ('in_transit', 'in_transit'), ('delivered', 'delivered')], default='in_transit', max_length=20)),
                ('sender_name', models.CharField(max_length=10)),
                ('receiver_name', models.CharField(max_length=10)),
                ('pickup_code', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('locker_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paczkomatyapp.locker_slot')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('created', 'created'), ('placed_in_locker', 'placed_in_locker'), ('picked_up', 'picked_up')], max_length=20)),
                ('parcel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paczkomatyapp.parcel')),
            ],
        ),
    ]
