# Generated by Django 5.2.1 on 2025-05-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paczkomatyapp', '0005_parcel_size_alter_parcel_locker_slot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcellocker',
            name='number_of_slots',
        ),
        migrations.AddField(
            model_name='parcellocker',
            name='large_slots',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='parcellocker',
            name='medium_slots',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='parcellocker',
            name='small_slots',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
