# Generated by Django 5.2.1 on 2025-05-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paczkomatyapp', '0006_remove_parcellocker_number_of_slots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('preparing', 'Preparing'), ('awaiting_pickup', 'Awaiting Pickup'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], default='preparing', max_length=30),
        ),
    ]
