# Generated by Django 5.2.1 on 2025-05-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paczkomatyapp', '0007_alter_parcel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcellocker',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
        migrations.AlterField(
            model_name='parcellocker',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
    ]
