# Generated by Django 5.2.1 on 2025-05-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paczkomatyapp', '0010_alter_parcellocker_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcellocker',
            name='latitude',
            field=models.DecimalField(decimal_places=20, max_digits=30),
        ),
        migrations.AlterField(
            model_name='parcellocker',
            name='longitude',
            field=models.DecimalField(decimal_places=20, max_digits=30),
        ),
    ]
